bucket check in actions

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -22,5 +22,24 @@ jobs:
           aws-region: eu-central-1
 
       - name: Deploy to S3 bucket
-        run: aws s3 sync ./website/ s3://${{ secrets.S3_BUCKET }} --delete
-        continue-on-error: true
+        run: |
+          echo "Checking S3 bucket exists..."
+          BUCKET_EXISTS=true
+          S3_CHECK=$(aws s3 ls "s3://${{ secrets.S3_BUCKET }}" 2>&1)
+
+          #Some sort of error happened with s3 check
+          if [ $? != 0 ]
+          then
+            NO_BUCKET_CHECK=$(echo $S3_CHECK | grep -c 'NoSuchBucket')
+            if [ $NO_BUCKET_CHECK = 1 ]; then
+              echo "Bucket does not exist"
+              BUCKET_EXISTS=false
+            else
+              echo "Error checking S3 Bucket"
+              echo "$S3_CHECK"
+              exit 1
+            fi
+          else
+            echo "Bucket exists"
+            aws s3 sync ./website/ s3://${{ secrets.S3_BUCKET }} --delete
+          fi
